const fs = require('fs');
const path = require('path');
const { initDB, getDB } = require('./config/db');

function escapeSqlValue(val) {
  if (val === null || val === undefined) return 'NULL';
  if (typeof val === 'number') return String(val);
  if (typeof val === 'boolean') return val ? 'TRUE' : 'FALSE';
  if (Buffer.isBuffer(val)) return `decode('${val.toString('hex')}', 'hex')`;
  if (val instanceof Date) return `'${val.toISOString()}'`;
  return `'${String(val).replace(/'/g, "''")}'`;
}

async function exportDump() {
  await initDB();
  const db = getDB();

  let sql = `-- ========================================================
-- SmartBus Cloud Supabase Database Initialization & Migration
-- Project: SWE_ECOM (ID: ylkbeildfsqpgccwgcwa)
-- Generated: ${new Date().toISOString()}
-- ========================================================

-- 1. SCHEMAS & EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 2. TABLES DDL
CREATE TABLE IF NOT EXISTS institutes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  address TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'student',
  phone TEXT,
  must_change_password INTEGER NOT NULL DEFAULT 1,
  token_version INTEGER NOT NULL DEFAULT 0,
  institute_id INTEGER REFERENCES institutes(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'active',
  suspension_reason TEXT,
  access_start TEXT,
  access_end TEXT,
  avatar_data BYTEA,
  avatar_mime TEXT
);

CREATE TABLE IF NOT EXISTS routes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  stops TEXT NOT NULL,
  etas TEXT NOT NULL,
  stop_coordinates TEXT NOT NULL DEFAULT '[]',
  institute_id INTEGER REFERENCES institutes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS buses (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  number_plate TEXT UNIQUE NOT NULL,
  driver_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  route TEXT,
  lat DOUBLE PRECISION,
  lng DOUBLE PRECISION,
  status TEXT DEFAULT 'On time',
  current_stop TEXT,
  departure_time TEXT,
  institute_id INTEGER REFERENCES institutes(id) ON DELETE CASCADE,
  route_id INTEGER REFERENCES routes(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS payments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  institute_id INTEGER NOT NULL REFERENCES institutes(id) ON DELETE CASCADE,
  amount_cents INTEGER NOT NULL CHECK(amount_cents > 0),
  currency TEXT NOT NULL DEFAULT 'PKR',
  access_start TEXT NOT NULL,
  access_end TEXT NOT NULL,
  reference TEXT NOT NULL DEFAULT '',
  recorded_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS app_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS policy_documents (
  type TEXT PRIMARY KEY CHECK(type IN ('privacy','terms')),
  original_name TEXT NOT NULL,
  mime_type TEXT NOT NULL DEFAULT 'application/pdf',
  file_data BYTEA NOT NULL,
  uploaded_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contact_inquiries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  organization TEXT NOT NULL DEFAULT '',
  designation TEXT NOT NULL DEFAULT '',
  service TEXT NOT NULL DEFAULT 'General enquiry',
  message TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'unread' CHECK(status IN ('unread','read','resolved')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 3. INDEXES & CONSTRAINTS
CREATE UNIQUE INDEX IF NOT EXISTS one_admin_per_institute ON users(institute_id) WHERE role = 'admin';
CREATE UNIQUE INDEX IF NOT EXISTS routes_institute_name ON routes(institute_id, name);
CREATE INDEX IF NOT EXISTS users_institute_role ON users(institute_id, role);
CREATE INDEX IF NOT EXISTS buses_institute ON buses(institute_id);
CREATE INDEX IF NOT EXISTS routes_institute ON routes(institute_id);
CREATE INDEX IF NOT EXISTS payments_student ON payments(student_id);
CREATE INDEX IF NOT EXISTS contact_inquiries_status_created ON contact_inquiries(status, created_at DESC);

-- 4. SUPABASE POSTGREST PERMISSIONS & GRANTS
GRANT USAGE ON SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL ROUTINES IN SCHEMA public TO postgres, anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO postgres, anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres, anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON ROUTINES TO postgres, anon, authenticated, service_role;

-- 5. DATA MIGRATION INSERTS
`;

  const tables = ['institutes', 'users', 'routes', 'buses', 'payments', 'app_settings', 'policy_documents', 'contact_inquiries'];
  
  for (const table of tables) {
    let rows = [];
    try {
      rows = await db.all(`SELECT * FROM ${table} ORDER BY ${table === 'app_settings' ? 'key' : 'id'}`);
    } catch {
      continue;
    }

    if (rows.length === 0) continue;

    sql += `\n-- --------------------------------------------------------\n`;
    sql += `-- Data for table: ${table} (${rows.length} rows)\n`;
    sql += `-- --------------------------------------------------------\n`;

    const cols = Object.keys(rows[0]);
    for (const row of rows) {
      const vals = cols.map(c => escapeSqlValue(row[c])).join(', ');
      const conflict = table === 'app_settings'
        ? ' ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value'
        : (cols.includes('id') ? ' ON CONFLICT (id) DO NOTHING' : '');
      
      sql += `INSERT INTO ${table} (${cols.join(', ')}) VALUES (${vals})${conflict};\n`;
    }

    if (cols.includes('id')) {
      sql += `SELECT setval(pg_get_serial_sequence('${table}', 'id'), COALESCE((SELECT MAX(id) FROM ${table}), 1), (SELECT COUNT(*) > 0 FROM ${table}));\n`;
    }
  }

  const dumpPath = path.resolve(__dirname, 'supabase_dump.sql');
  fs.writeFileSync(dumpPath, sql, 'utf8');
  console.log(`Successfully generated ${dumpPath} (${(fs.statSync(dumpPath).size / 1024).toFixed(1)} KB)`);
  await db.close();
}

exportDump().catch(err => {
  console.error('Export failed:', err);
  process.exit(1);
});
